### ISSUE TITLE
AppCenter SDK for Xamarin.Mac

### ISSUE THREAD

**Issue by nor0x** [alexsorokoletov/objc-automatic#19]
I'm trying to create bindings for the Cocoapod [AppCenter](https://cocoapods.org/pods/AppCenter) SDK because I would like to use it with Xamarin.Mac. I modified `build.fsx` and added `CODE_SIGNING_ALLOWED=NO` to support the latest version of Xcode. I also had to set `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`.

With these options the build finishes without any errors, but i get two `VERIFY:` messages and the all the directories in the `bindings` folders are empty.
```
Finished Target: Bind

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Bind       00:00:06.3800139
Total:     00:00:06.4176695
---------------------------------------------------------------------
Status:    Ok

```
Now I'm stuck with the following two error messages:

```
VERIFY: pod AppCenter doesn't have any binaries generated for config  -sdk "iphoneos"
VERIFY: pod AppCenter most probably doesn't have any binaries generated
```

Anyone who can help me out with this one?
Thanks

**Comment by alexsorokoletov** [comment]
@nor0x I'll be happy to help, let me take a look. 
`objc-automatic` can't help with Mac bindings. What parts of the SDK do you need?

**Comment by nor0x** [comment]
Thanks @alexsorokoletov. I'm working on AppCenter.Analytics and AppCenter.Crashes

**Comment by alexsorokoletov** [comment]
@nor0x I looked at the MacOS support for AppCenter SDK.
It is pretty straightforward MacOS Xamarin binding.
My recommendation would be to start from this thread https://github.com/microsoft/appcenter-sdk-dotnet/issues/529 and this repo https://github.com/apparentvisuals/AppCenter-SDK-DotNet/tree/develop/SDK/AppCenter (or this PR https://github.com/microsoft/appcenter-sdk-dotnet/pull/658)

You can get the binding projects from these places or make them yourself. After that, you could use the latest AppCenter for MacOS release https://github.com/Microsoft/AppCenter-SDK-Apple/releases and you'll have a Xamarin MacOS project with latest and greatest.

Good luck and I would recommend open-sourcing that project right here on Github, it'd be great!

**Comment by nor0x** [comment]
thanks for the info 👍 
i will look into it

**Comment by DennisWelu** [comment]
@nor0x Did you move ahead with anything for MacOS yet?
