### ISSUE TITLE
Error during pod install

### ISSUE THREAD

**Issue by sfmskywalker** [alexsorokoletov/objc-automatic#8]
Hi! When I try the objc-automatic tool, I'm always getting a "Error during pod install" error. I must have missed something, but I can't figure it out. Can you help? Here's my bash log:

![image](https://user-images.githubusercontent.com/938393/33769277-d6ad7742-dc29-11e7-86c0-020c3a5e2306.png)

**Comment by alexsorokoletov** [comment]
@sfmskywalker Thanks for trying the tool! 
Can you please do two things:
- verify you have all prerequisites installed
- repeat your command one more time with additional parameter VERBOSE=true.

**Comment by sfmskywalker** [comment]
Thank you for your prompt response!

- I made sure all prerequisites are installed.
- I repeated the command, but this time with VERBOSE=true.

Here is the updated result:

![image](https://user-images.githubusercontent.com/938393/33781331-745ed452-dc54-11e7-9dc3-9263ee4af6c4.png)

It looks like the issue is with **CocoaPods** not allowed to run as root, because right after that program finished its help output, the "Running build failed" message appears.

I'll see if I can execute the command with my own user, making sure my user has sufficient access.
Should you have any additional insight, I would obviously love to hear it.

I'll report back shortly.

**Comment by sfmskywalker** [comment]
Quick update: when I run the command without sudo, I get an Access Denied exception:

![image](https://user-images.githubusercontent.com/938393/33781522-4048422e-dc55-11e7-931d-ee4d75d15a43.png)

But what I don't quite understand is why, since I gave read&write permissions to "everyone". I'll be on Google if you're looking for me ;)

**Comment by alexsorokoletov** [comment]
@sfmskywalker

I think the last one error is because you first ran everything as sudo, app created all the files as sudo. Then you ran command as normal user and it failed. Easiest would be just to delete folder and clone it again. Then redo everything as normal user. No sudo required.

**Comment by sfmskywalker** [comment]
Dude that was it. Thank you for being so awesome! I owe you a beer.
